name = "blog"
main = "./.output/server/index.mjs"
compatibility_date = "2023-10-25"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

minify = true

[site]
bucket = ".output/public"
