name: New commit event

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'posts/**'
jobs:
  Send notification:
    name: Send message
    runs-on: ubuntu-latest
    steps:
    - uses: colutius/Telegram-Msg@main
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        chatid: ${{ secrets.TELEGRAM_TO }}
        message: |
            ${{ github.repository }} 有新的内容提交。

            内容类型：站点代码修改

            提交人: ${{ github.actor }}

            提交信息: ${{ github.event.commits[0].message }}
        button: true
        button_name: 查看 Commit 详情
        button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        is_notify: true
        is_preview: true